// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// p_correction
arma::colvec p_correction(const arma::colvec& pa, const arma::colvec& p0, const bool& log10p);
RcppExport SEXP _distQTL_p_correction(SEXP paSEXP, SEXP p0SEXP, SEXP log10pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type pa(paSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< const bool& >::type log10p(log10pSEXP);
    rcpp_result_gen = Rcpp::wrap(p_correction(pa, p0, log10p));
    return rcpp_result_gen;
END_RCPP
}
// scaleX_cpp
arma::mat scaleX_cpp(const arma::mat& X, const double& tol);
RcppExport SEXP _distQTL_scaleX_cpp(SEXP XSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleX_cpp(X, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_distQTL_p_correction", (DL_FUNC) &_distQTL_p_correction, 3},
    {"_distQTL_scaleX_cpp", (DL_FUNC) &_distQTL_scaleX_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_distQTL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
