# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scaleX_cpp <- function(X, tol = 1e-10) {
    .Call(`_distQTL_scaleX_cpp`, X, tol)
}

