# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

p_correction <- function(pa, p0, log10p = TRUE) {
    .Call(`_distQTL_p_correction`, pa, p0, log10p)
}

scaleX_cpp <- function(X, tol = 1e-10) {
    .Call(`_distQTL_scaleX_cpp`, X, tol)
}

sumC <- function(M, E) {
    .Call(`_distQTL_sumC`, M, E)
}

